language: python
dist: bionic
python:
  - "3.7-dev"
  - "3.8-dev"
  - "3.9"
  - "3.9-dev"
  - "3.10" # 3.10
    #- "nightly"  # nightly build
# command to install dependencies
install:
  - python -m venv .
  - . bin/activate
  - pip install -r requirements.txt
  - pip install -e .
# command to run tests
script:
  - bash test_run.sh
