language: python
python:
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
    #- "nightly"  # nightly build
# command to install dependencies
install:
  - python -m venv .
  - . bin/activate
  - pip install -r requirements.txt
  - pip install -e .
# command to run tests
script:
  - bash runtest.sh
